/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 corn.glb -T 
Files: corn.glb [284.93KB] > D:\hitha_web\public\models\corn-transformed.glb [32.86KB] (88%)
Author: Tiia Tuulia (https://sketchfab.com/tiiatuulia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/corn-corn-corn-10187bc37c9e42ef8770b28452ee7cd3
Title: Corn! Corn! Corn!
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function CornModel(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/corn-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.624}>
          <group name="Circle_020" position={[0.038, 3.448, 0.089]} rotation={[-1.593, 0.017, 2.342]} scale={0.084}>
            <mesh name="Circle_020_corn_plant__corn_texture_png_0" geometry={nodes.Circle_020_corn_plant__corn_texture_png_0.geometry} material={materials.corn_plant__corn_texture_png} />
            <mesh name="Circle_020_corn_plant_001__corn_texture_png_001_0" geometry={nodes.Circle_020_corn_plant_001__corn_texture_png_001_0.geometry} material={materials.corn_plant_001__corn_texture_png_001} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/corn-transformed.glb')
