/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sugar.glb -T 
Files: sugar.glb [7.67MB] > D:\hitha_web\public\models\sugar-transformed.glb [784.45KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function SugarModel(props) {
  const { nodes, materials } = useGLTF('/models/sugar-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.YVO3Dobj.geometry} material={materials.PBR_Material} />
    </group>
  )
}

useGLTF.preload('/sugar-transformed.glb')
